kind = "api"
previewPath = "/"
title = "ANONYMIKETECH"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/"]

[services.development]
run = "node index.js"

[services.development.env]
PORT = "8080"
NODE_ENV = "production"
SERVE_STATIC = "true"

[services.production]

[services.production.run]
args = ["node", "index.js"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"
SERVE_STATIC = "true"

[services.production.health.startup]
path = "/"
